## Installation of Numpy 

In [2]:
# pip install numpy 

## Installation of Pandas

In [3]:
#pip install pandas

##### Creating Array 

In [5]:
import numpy as np

In [6]:
np.array([2,3,4])

array([2, 3, 4])

##### Data Tpye of Array 

In [8]:
np.array([2,4,5],dtype="int64")

array([2, 4, 5], dtype=int64)

In [9]:
np.array([2,4,5],dtype="float64")

array([2., 4., 5.])

##### Array indexing
 Field Access <br>
 Slicing
 

###### Field Access 

In [10]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])

In [11]:
x['a'].shape

(3, 3)

In [13]:
x['b'].dtype

dtype('float64')

###### Slicing

In [14]:
e=np.array([1,2,3,4,5,6])

In [15]:
e

array([1, 2, 3, 4, 5, 6])

In [16]:
e[1:-1:2]

array([2, 4])

##### Mathmatical Operation 

In [17]:
e.sum()

21

In [18]:
e.max()

6

In [19]:
e.mean()

3.5

##### Broadcasting 
Broadcasting enables arithmetic operations to be performed between different shaped arrays.

In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v=np.array([1,0,1])

In [21]:
b=a+v

In [22]:
b

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

## Pandas

In [23]:
# pip install pandas 

##### Creating DataFrame

In [28]:
df = {'Gender': ['F', 'M', 'M'],'Emp_ID': ['E01', 'E02', 'E03'],'Age': [25, 27, 25]}

In [29]:
df

{'Gender': ['F', 'M', 'M'],
 'Emp_ID': ['E01', 'E02', 'E03'],
 'Age': [25, 27, 25]}

##### Reading and Writing Data

In [1]:
import pandas as pd

In [4]:
df= pd.read_csv("heart_disease_dataset.csv")

In [5]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
5     56    1   2       120   236    0        0      178      0      0.8   
6     62    0   4       140   268    0        2      160      0      3.6   
7     57    0   4       120   354    0        0      163      1      0.6   
8     63    1   4       130   254    0        2      147      0      1.4   
9     53    1   4       140   203    1        2      155      1      3.1   
10    57    1   4       140   192    0        0      148      0      0.4   
11    56    0   2       140   294    0        2      153      0      1.3   
12    56    1   3       130   256    1        2      142      1      0.6   
13    44    1   2       120   263    0        0      173      0      0.0   
14    52    1   3       172   199    1        0      162      0      0.5   
15    57    1   3       150   168    0        0      174      0      1.6   
16    48    1   2       110   229    0        0      168      0      1.0   
17    54    1   4       140   239    0        0      160      0      1.2   
18    48    0   3       130   275    0        0      139      0      0.2   
19    49    1   2       130   266    0        0      171      0      0.6   
20    64    1   1       110   211    0        2      144      1      1.8   
21    58    0   1       150   283    1        2      162      0      1.0   
22    58    1   2       120   284    0        2      160      0      1.8   
23    58    1   3       132   224    0        2      173      0      3.2   
24    60    1   4       130   206    0        2      132      1      2.4   
25    50    0   3       120   219    0        0      158      0      1.6   
26    58    0   3       120   340    0        0      172      0      0.0   
27    66    0   1       150   226    0        0      114      0      2.6   
28    43    1   4       150   247    0        0      171      0      1.5   
29    40    1   4       110   167    0        2      114      1      2.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
273   71    0   4       112   149    0        0      125      0      1.6   
274   59    1   1       134   204    0        0      162      0      0.8   
275   64    1   1       170   227    0        2      155      0      0.6   
276   66    0   3       146   278    0        2      152      0      0.0   
277   39    0   3       138   220    0        0      152      0      0.0   
278   57    1   2       154   232    0        2      164      0      0.0   
279   58    0   4       130   197    0        0      131      0      0.6   
280   57    1   4       110   335    0        0      143      1      3.0   
281   47    1   3       130   253    0        0      179      0      0.0   
282   55    0   4       128   205    0        1      130      1      2.0   
283   35    1   2       122   192    0        0      174      0      0.0   
284   61    1   4       148   203    0        0      161      0      0.0   
285   58    1   4       114   318    0        1      140      0      4.4   
286   58    0   4       170   225    1        2      146      1      2.8   
287   58    1   2       125   220    0        0      144      0      0.4   
288   56    1   2       130   221    0        2      163      0      0.0   
289   56    1   2       120   240    0        0      169      0      0.0   
290   67    1   3       152   212    0        2      150      0      0.8   
291   55    0   2       132   342    0        0      166      0      1.2   
292   44    1   4       120   169    0        0      144      1      2.8   
293   63    1   4       140   187    0        2      

In [6]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  num  
0   0     6    0  
1   3     3    1  
2   2     7    1  
3   0     3    0  
4   0     3    0

In [7]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope  \
count  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660   
std      0.994971   22.875003    0.469794    1.161075    0.616226   
min      0.000000   71.000000    0.000000    0.000000    1.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000   

                  ca           thal         num  
count     303.000000     303.000000  303.000000  
mean    -1319.468647    -655.363036    0.458746  
std     11432.566205    8111.366638    0.499120  
min   -100000.000000 -100000.000000    0.000000  
25%         0.000000       3.000000    0.000000  
50%         0.000000       3.000000    0.000000  
75%         1.000000       7.000000    1.000000  
max         3.000000       7.000000    1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
num         303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.2 KB


##### Concat

In [9]:
X=df['age']

In [16]:
df1=pd.concat([df,X])

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\api.py:107: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  result = result.union(other)


In [13]:
df1

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0    63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
5    56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
6    62.0  0.0  4.0     140.0  268.0  0.0      2.0    160.0    0.0      3.6   
7    57.0  0.0  4.0     120.0  354.0  0.0      0.0    163.0    1.0      0.6   
8    63.0  1.0  4.0     130.0  254.0  0.0      2.0    147.0    0.0      1.4   
9    53.0  1.0  4.0     140.0  203.0  1.0      2.0    155.0    1.0      3.1   
10   57.0  1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
11   56.0  0.0  2.0     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
12   56.0  1.0  3.0     130.0  256.0  1.0      2.0    142.0    1.0      0.6   
13   44.0  1.0  2.0     120.0  263.0  0.0      0.0    173.0    0.0      0.0   
14   52.0  1.0  3.0     172.0  199.0  1.0      0.0    162.0    0.0      0.5   
15   57.0  1.0  3.0     150.0  168.0  0.0      0.0    174.0    0.0      1.6   
16   48.0  1.0  2.0     110.0  229.0  0.0      0.0    168.0    0.0      1.0   
17   54.0  1.0  4.0     140.0  239.0  0.0      0.0    160.0    0.0      1.2   
18   48.0  0.0  3.0     130.0  275.0  0.0      0.0    139.0    0.0      0.2   
19   49.0  1.0  2.0     130.0  266.0  0.0      0.0    171.0    0.0      0.6   
20   64.0  1.0  1.0     110.0  211.0  0.0      2.0    144.0    1.0      1.8   
21   58.0  0.0  1.0     150.0  283.0  1.0      2.0    162.0    0.0      1.0   
22   58.0  1.0  2.0     120.0  284.0  0.0      2.0    160.0    0.0      1.8   
23   58.0  1.0  3.0     132.0  224.0  0.0      2.0    173.0    0.0      3.2   
24   60.0  1.0  4.0     130.0  206.0  0.0      2.0    132.0    1.0      2.4   
25   50.0  0.0  3.0     120.0  219.0  0.0      0.0    158.0    0.0      1.6   
26   58.0  0.0  3.0     120.0  340.0  0.0      0.0    172.0    0.0      0.0   
27   66.0  0.0  1.0     150.0  226.0  0.0      0.0    114.0    0.0      2.6   
28   43.0  1.0  4.0     150.0  247.0  0.0      0.0    171.0    0.0      1.5   
29   40.0  1.0  4.0     110.0  167.0  0.0      2.0    114.0    1.0      2.0   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
273   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
274   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
275   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
276   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
277   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
278   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
279   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
280   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
281   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
282   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
283   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
284   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
285   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
286   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
287   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
288   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
289   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
290   NaN  NaN  NaN       NaN    NaN  NaN      NaN      NaN    NaN      NaN   
291   NaN  NaN  NaN       NaN    NaN  NaN      NaN      